CREATE EXTERNAL TABLE IF NOT EXISTS db_work_${DATALAKE_ENV}.ais_objdata_tmp_et(
country_sid STRING,
objno STRING,
validfrom STRING,
validto STRING,
storeno STRING,
typeid STRING,
typeid_isos STRING,
delivcmp STRING,
delivdt STRING,
takecmp STRING,
takedt STRING,
proprid STRING,
propid STRING,
takeobj STRING,
delivobj STRING,
areakey STRING,
gradid STRING,
employds STRING,
employsv STRING,
employst STRING,
assistant1 STRING,
assistant2 STRING,
assistant3 STRING,
substitut1 STRING,
substitut2 STRING,
substitut3 STRING,
buiapply STRING,
constrdt STRING,
planopen STRING,
opendt STRING,
planclos STRING,
closedt STRING,
ownused STRING,
zoneyn STRING,
unsettl STRING,
saleddt STRING,
descript STRING,
street STRING,
zipcode STRING,
statzipc STRING,
town STRING,
postbox STRING,
telefon STRING,
telefax STRING,
surfause STRING,
surfatot STRING,
buigrnd STRING,
surfatra STRING,
carpkout STRING,
areauset STRING,
areauses STRING,
surfaext STRING,
surfasis STRING,
volbuild STRING,
cstplid STRING,
dcstplid STRING,
depreplc STRING,
areawhse STRING,
areaused STRING,
areausea STRING,
areadepg STRING,
areadepn STRING,
areacst STRING,
areadcst STRING,
surfasid STRING,
reserve STRING,
tmp_closedt STRING,
tmp_opendt STRING,
roofid STRING,
change_date STRING,
change_user STRING,
create_date STRING,
create_user STRING,
update_id STRING,
subleasedparkingspaces STRING,
legalentity STRING,
suitable4disabledpersons STRING,
taxfree STRING,
carpark STRING,
bakeoff STRING,
beer STRING,
wine STRING,
petrolstation STRING,
nooftills STRING,
noofdepositmachines STRING,
servicehotlinenumber STRING,
geographicalcoordinatesstorelongtitude STRING,
geographicalcoordinatesstorelatitude STRING,
openinghoursmondayfrom1 STRING,
openinghoursmondayto1 STRING,
openinghoursmondayfrom2 STRING,
openinghoursmondayto2 STRING,
openinghourstuesdayfrom1 STRING,
openinghourstuesdayto1 STRING,
openinghourstuesdayfrom2 STRING,
openinghourstuesdayto2 STRING,
openinghourswednesdayfrom1 STRING,
openinghourswednesdayto1 STRING,
openinghourswednesdayfrom2 STRING,
openinghourswednesdayto2 STRING,
openinghoursthursdayfrom1 STRING,
openinghoursthursdayto1 STRING,
openinghoursthursdayfrom2 STRING,
openinghoursthursdayto2 STRING,
openinghoursfridayfrom1 STRING,
openinghoursfridayto1 STRING,
openinghoursfridayfrom2 STRING,
openinghoursfridayto2 STRING,
openinghourssaturdayfrom1 STRING,
openinghourssaturdayto1 STRING,
openinghourssaturdayfrom2 STRING,
openinghourssaturdayto2 STRING,
openinghourssundayfrom1 STRING,
openinghourssundayto1 STRING,
openinghourssundayfrom2 STRING,
openinghourssundayto2 STRING,
specialopeninghoursonmonday STRING,
specialopeninghoursontuesday STRING,
specialopeninghoursonwednesday STRING,
specialopeninghoursonthursday STRING,
specialopeninghoursonfriday STRING,
specialopeninghoursonsaturday STRING,
specialopeninghoursonsunday STRING,
specialopeninghourscomment STRING,
announcementgrandopening STRING,
objectcomment STRING,
notation STRING,
planopenexternalusage STRING,
openexternalusage STRING,
plancloseexternalusage STRING,
closeexternalusage STRING,
objectusageid STRING,
relatedobjectno STRING,
subaccountno STRING,
liquorlicensecommencementdate STRING,
reconstructionafterdemolition STRING,
demolitiondate STRING,
additionalphonenumber STRING,
streetlong STRING,
dataowner STRING,
zones STRING
) 
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\001'
LOCATION '/tmp/${DATALAKE_ENV}_extract_ais_objdata';

SET hive.exec.dynamic.partition.mode=nonstrict;

SET mapred.output.compression.codec=org.apache.hadoop.io.compress.SnappyCodec; 
SET parquet.compression=snappy;

--replace entire table (no partitions)
INSERT OVERWRITE TABLE db_ais_${DATALAKE_ENV}.la_ais_objdata_et PARTITION (business_date)
SELECT 
country_sid,
objno,
validfrom,
validto,
storeno,
typeid,
typeid_isos,
delivcmp,
delivdt,
takecmp,
takedt,
proprid,
propid,
takeobj,
delivobj,
areakey,
gradid,
CASE WHEN country_sid NOT IN ('3', '6')
THEN mask_show_last_n(employds, 3, 'X', 'X', 'X')
ELSE employds END AS employds,
CASE WHEN country_sid NOT IN ('3', '6')
THEN mask_show_last_n(employsv, 3, 'X', 'X', 'X')
ELSE employsv END AS employsv,
CASE WHEN country_sid NOT IN ('3', '6')
THEN mask_show_last_n(employst, 3, 'X', 'X', 'X')
ELSE employst END AS employst,
assistant1,
assistant2,
assistant3,
substitut1,
substitut2,
substitut3,
buiapply,
constrdt,
planopen,
opendt,
planclos,
closedt,
ownused,
zoneyn,
unsettl,
saleddt,
descript,
street,
zipcode,
statzipc,
town,
postbox,
telefon,
telefax,
surfause,
surfatot,
buigrnd,
surfatra,
carpkout,
areauset,
areauses,
surfaext,
surfasis,
volbuild,
cstplid,
dcstplid,
depreplc,
areawhse,
areaused,
areausea,
areadepg,
areadepn,
areacst,
areadcst,
surfasid,
reserve,
tmp_closedt,
tmp_opendt,
roofid,
change_date,
change_user,
create_date,
create_user,
update_id,
subleasedparkingspaces,
legalentity,
suitable4disabledpersons,
taxfree,
carpark,
bakeoff,
beer,
wine,
petrolstation,
nooftills,
noofdepositmachines,
servicehotlinenumber,
geographicalcoordinatesstorelongtitude,
geographicalcoordinatesstorelatitude,
openinghoursmondayfrom1,
openinghoursmondayto1,
openinghoursmondayfrom2,
openinghoursmondayto2,
openinghourstuesdayfrom1,
openinghourstuesdayto1,
openinghourstuesdayfrom2,
openinghourstuesdayto2,
openinghourswednesdayfrom1,
openinghourswednesdayto1,
openinghourswednesdayfrom2,
openinghourswednesdayto2,
openinghoursthursdayfrom1,
openinghoursthursdayto1,
openinghoursthursdayfrom2,
openinghoursthursdayto2,
openinghoursfridayfrom1,
openinghoursfridayto1,
openinghoursfridayfrom2,
openinghoursfridayto2,
openinghourssaturdayfrom1,
openinghourssaturdayto1,
openinghourssaturdayfrom2,
openinghourssaturdayto2,
openinghourssundayfrom1,
openinghourssundayto1,
openinghourssundayfrom2,
openinghourssundayto2,
specialopeninghoursonmonday,
specialopeninghoursontuesday,
specialopeninghoursonwednesday,
specialopeninghoursonthursday,
specialopeninghoursonfriday,
specialopeninghoursonsaturday,
specialopeninghoursonsunday,
specialopeninghourscomment,
announcementgrandopening,
objectcomment,
notation,
planopenexternalusage,
openexternalusage,
plancloseexternalusage,
closeexternalusage,
objectusageid,
relatedobjectno,
subaccountno,
liquorlicensecommencementdate,
reconstructionafterdemolition,
demolitiondate,
additionalphonenumber,
streetlong,
dataowner,
zones,
regexp_replace(substr(CAST(current_timestamp() AS STRING), 1, 10), '-', '') AS business_date
  FROM db_work_${DATALAKE_ENV}.ais_objdata_tmp_et;

MSCK REPAIR TABLE db_ais_${DATALAKE_ENV}.la_ais_objdata_et;

DROP TABLE db_work_${DATALAKE_ENV}.ais_objdata_tmp_et;